### ISSUE TITLE
استخدام عناصر من المشروع في صور ويكيبيديا

### ISSUE THREAD

**Issue by hubaishan** [DigitalKhatt/digitalkhatt.org#13]
السلام عليكم ورحمة الله وبركاته

استخدمت برواز اسم السورة في صور للسور في ويكيبيديا ونشرتها على كومنزhttps://commons.wikimedia.org/wiki/File:Quran-soura-112.svg ، فهل الترخيص يسمح بذلك أم يتوجب تغيير الترخيص أو حذف البرواز

**Comment by aminanan** [comment]
No problem. Thanks for asking.
